### ISSUE TITLE
可以增加逐字显示的功能吗？

### ISSUE THREAD

**Issue by AnanasJin** [vastsa/AIChatWeb#4]
逐字显示能明显减少输出长文字时的等待感，希望作者能考虑增加这个功能

**Comment by ThePeppy** [comment]
附议，还有高级版的js文件不应该加密了，购买了之后 感觉又没有一样

**Comment by vastsa** [comment]
> 

没有加密哦，这是vue打包之后的，晚点我在云盘上放出vue源码

**Comment by vastsa** [comment]
> 逐字显示能明显减少输出长文字时的等待感，希望作者能考虑增加这个功能

这个其实没啥用，因为接口返回都是一次性直接返回的，加个这个只能延长等待时间

**Comment by vastsa** [comment]
> 附议，还有高级版的js文件不应该加密了，购买了之后 感觉又没有一样

<img width="676" alt="image" src="https://user-images.githubusercontent.com/48862574/218635932-cc420b6d-fb5a-493f-b45f-703c7583d37f.png">
已经上传啦
